#!/bin/bash
# Sidux-Control-Center
# Fabian Wuertz
# siduxcc based on knxcc_info from Andreas Loible
# License: GPL


#run gettext
. /usr/bin/gettext.sh

testRoot()
{
	if (($UID)); then
		echo $(eval_gettext "Error: You must be root to run this script!")
		exit 1
	fi
}

SEARCHPATH="/usr/share/siduxcc"

export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=siduxccccscript

MODULES="\\"; export MODULES
function register_module()
{
	MODULES2="$MODULES2 $2"
}

BACKDIR="$PWD"
cd "$SEARCHPATH"

argc="$#";
module="$1"; shift
case $argc in
0|1)
    # Include all Modules
    for source_module in $(find modules -name '*.bm')
    do
        . "$source_module" || exit 3
    done
	. scripts/loadssft.sh
    if [ -z "$module" ]; then
        . "modules/interface"
    else
        eval "${module}_interface"
    fi
    ;;
about)
     about;;
*)
    # Include supplied Module
    action="$1"; shift
    case $action in
        ssft*)
            . scripts/loadssft.sh
            testRoot;;
    esac
    . modules/"$module".bm || exit 3

    if [ "$action" ]; then
        "$action" "$@"
        RC=$?
        if [ $RC -ne 0 ]; then
            exit $RC
        fi
    fi
    ;;
esac
cd "$BACKDIR"

exit 0
# exitcodes
cat <<=  1>&2
0: OK
1: UID not root
2: Usage (wrong syntax?)
3: Module not found
4: Module: bad sub/function
=
