debian/tmp/usr/bin/siduxcc-kde3                               usr/bin/
debian/tmp/usr/bin/sidux-hermes-kde3                             usr/bin/
debian/tmp/usr/share/applications/kde/siduxcc-kde3.desktop         usr/share/applications/kde/
debian/tmp/usr/share/applications/kde/sidux-hermes-kde3.desktop  usr/share/applications/kde/
debian/tmp/usr/share/siduxcc/icons                            usr/share/siduxcc/
debian/tmp/usr/share/siduxcc/hermes                           usr/share/siduxcc/
