#!/bin/bash
# (C) 2007 by Fabian Wrtz
# License: GPL

if [ "$UID" -ne 0 ]; then
        echo 'You must run this as root!'
        exit 1
fi

TMP=`ls /etc/X11/xorg.conf-* | tail -n 1`

if [ "$TMP" = "" ]; then
  exit
fi

read -p "Do you want restore $TMP? <yes/no>"
if [ "$REPLY" = "yes" ]; then
  cp -f $TMP /etc/X11/xorg.conf
  nohup /usr/share/siduxcc/restartx.sh
else
  exit
fi

